# Generated by Django 4.1.3 on 2022-11-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
