# Generated by Django 4.1.3 on 2022-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customer_email_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
