# Generated by Django 4.1.3 on 2022-11-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemTrue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('status', models.CharField(choices=[('SHI', 'Shipped'), ('DEL', 'Out for Delivery'), ('NOT', 'No Info')], default='SHI', max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
