# Generated by Django 4.1.3 on 2022-12-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtrue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
